name: Publish to NuGet

on:
  push:
    branches:
      - main  # Trigger the workflow on push or pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/WebSecurityMiddleware/WebSecurityMiddleware.csproj

    - name: Build
      run: dotnet build ./src/WebSecurityMiddleware/WebSecurityMiddleware.csproj --no-restore

    - name: Test
      run: dotnet test ./test/WebSecurityMiddleware.UnitTests/WebSecurityMiddleware.UnitTests.csproj --no-build --verbosity normal

    - name: Pack
      run: dotnet pack ./src/WebSecurityMiddleware/WebSecurityMiddleware.csproj --no-build --output nupkg

    - name: Push
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}  # NuGet API key, you need to set this in your GitHub repository secrets
      run: dotnet nuget push ./nupkg/*.nupkg --skip-duplicate
