version: '3.8'
services:
  caddy:
    image: caddy:2.4.6-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - websecuritymiddleware.samplewebapi

  websecuritymiddleware.samplewebapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"