name: Publish to NuGet

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/WebSecurityMiddleware/WebSecurityMiddleware.csproj

    - name: Build
      run: dotnet build ./src/WebSecurityMiddleware/WebSecurityMiddleware.csproj --no-restore -c Release

    - name: Test
      run: dotnet test ./test/WebSecurityMiddleware.UnitTests/WebSecurityMiddleware.UnitTests.csproj

    - name: Pack
      run: dotnet pack ./src/WebSecurityMiddleware/WebSecurityMiddleware.csproj --no-build --output nupkg

    - name: Push
      run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
